### ISSUE TITLE
Kéo dư án về máy và chạy thử

### ISSUE THREAD

**Issue by kiminonawa1305** [kiminonawa1305/Ticket_Movie_Booking_NLU#2]
Kéo về chạy thử dự án trên điện thoại
Chỉ có giao diện chưa xử lý sự kiên
Các chức năng có thể chạy

1. Chuyển trang đăng nhập và đăng ký
2. Chức năng đăng nhập chưa xử lý. Muốn đăng nhập thi chỉ cần nhấn nút đăng nhập là có thể chuyển trang.
3. Các danh mục trong phần phân loại vé (chuyển bằng cách vuốt trái hoặc phải hoặc có thể nhân trên thanh Tab)

**Comment by LamHongPhong1401** [comment]
test comment

**Comment by john9101** [comment]
Đã xong

**Comment by ducvui2003** [comment]
mmmm

**Comment by ducvui2003** [comment]
mhvhmhv

**Comment by ducvui2003** [comment]
dsfzsfassaa

**Comment by kiminonawa1305** [comment]
Thằng nào kéo về test xong thì cmt 1 cái nha
có vấn đề gì thì cmt lên đây
Ae hạn chế làm việc trên zalo lại nha

**Comment by OzuSus** [comment]
đã xong

**Comment by john9101** [comment]
<img width="960" alt="image" src="https://github.com/kiminonawa1305/Ticket_Movie_Booking_NLU/assets/104410315/aa7ab9db-d4bc-460c-bc30-e0fb093da73a">

@kiminonawa1305  Đã clone về máy, nhưng gặp lỗi này mặc dù folder fragments trong view vẫn có

**Comment by kiminonawa1305** [comment]
@john9101 m là thằg nào đổi tên đi.
Nào m rãnh. Tao connect máy tính rồi fix cho
