### ISSUE TITLE
Thiết kế giao diện thống kê danh số bán vé. Admin

### ISSUE THREAD

**Issue by lamnguyen13052003** [kiminonawa1305/Ticket_Movie_Booking_NLU#33]
Thử viện hổ trợ vẽ biểu đồ
[Thư viện 1](https://github.com/AnyChart/AnyChart-Android/)
[Thư viện 2](https://github.com/PhilJay/MPAndroidChart?tab=readme-ov-file)

**Comment by LamHongPhong1401** [comment]
Link figma: https://www.figma.com/design/UjJ6IljSGZGN7xgnXg44B4/LTDD?node-id=7-83&t=XfrSgdouJphTZbXb-1

**Comment by lamnguyen13052003** [comment]
Oki nha
Làm luôn đi nhá
