### ISSUE TITLE
Thiếu kế trang hiển thị danh sách khách hàng. Admin

### ISSUE THREAD

**Issue by lamnguyen13052003** [kiminonawa1305/Ticket_Movie_Booking_NLU#35]

**Comment by NguyenHoangAnhDuong** [comment]
![image](https://github.com/kiminonawa1305/Ticket_Movie_Booking_NLU/assets/127371632/b01faf60-2975-4cba-8696-1d20d0ec8446)
https://www.figma.com/design/IBwvf5RD2XWDnB7E9y2DLZ/Trang-%C4%90%E1%BA%B7t-gi%E1%BB%9D-v%C3%A0-%C4%91%E1%BA%B7t-gh%E1%BA%BF-v%C3%A0-thanh-to%C3%A1n?node-id=0-1&t=BZ5QcTxZbzH4cWPo-0

**Comment by lamnguyen13052003** [comment]
2 nút xác nhận có tác dụng chó dì cho cái trang này...
Rồi tạo tài khoản giúp khách luôn à...
Ác dị pa...
Hiển thị thông tin gồm: STT, email, password (mã hóa gọn lại tầm 5 kí tự rồi ...), fullName, Phone. (Cái này t sai, cho t xin lỗi nhé) Hiển thị thông tin tràng ra bên ngoài luôn, cho phép cuộc ngang để xem nội dung rõ hơn.
Sửa lại giúp nha chú..
Nhìn thiết kế ae kìa. Đâu ai làm ác như mày đâu...

**Comment by NguyenHoangAnhDuong** [comment]
Oke để t sửa lại r t tạo anroid luôn
Không biết đâu có thấy quản lí bằng đt bao giờ đâu 
Tạo tài khoản cho nhân viên ( này bỏ hả)
Xác nhận lúc đầu là t định set top buttom mà giờ nghĩ lại set position cho nó đẹp
Oke để t fix

**Comment by NguyenHoangAnhDuong** [comment]
![image](https://github.com/kiminonawa1305/Ticket_Movie_Booking_NLU/assets/127371632/9ecb9351-bbec-467c-939d-2d8dfca53706)
